'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'ko' | 'en'

const translations: Record<Language, Record<string, string>> = {
  ko: {
    // App & Layout
    'app.title': 'Riviera Health Spa 예약 관리',
    'app.subtitle': 'Riviera Health Spa Booking System',
    'nav.today_schedule': '오늘의 근무현황',
    'nav.calendar': '예약 현황판 (달력)',
    'nav.list': '예약 목록 (리스트)',
    'nav.blacklist': '취소자 블랙리스트',
    'nav.schedule': '근무 여부 설정',
    'nav.pricing': '요금관리',
    'nav.priority': '우선순위 관리',
    'nav.role': '권한 관리',
    'nav.therapist': '마사지사 관리',
    'nav.employee': '프론트 직원 등록 관리',
    'nav.history': '변경 이력 조회',
    'nav.stats': '예약 현황 통계',
    'nav.logout': '로그아웃',
    'nav.login': '로그인',
    'user.role.manager': '관리자',
    'user.role.leader': '스태프 리더',
    'user.role.staff': '직원',
    'user.role.therapist': '마사지사',
    'user.syncing': '데이터를 동기화하는 중...',

    // Login
    'login.title': '시스템 로그인',
    'login.email': '이메일 주소',
    'login.password': '비밀번호',
    'login.submit': '로그인',
    'login.submitting': '로그인 중...',
    'login.error': '로그인에 실패했습니다. 이메일과 비밀번호를 확인해주세요.',
    'login.info': '관리자 비밀번호: 12345! / 직원 & 마사지사 비밀번호: 123456',

    // Calendar & Modes
    'calendar.title': '예약 현황판 (달력)',
    'calendar.mode.day': '일간',
    'calendar.mode.week': '주간',
    'calendar.mode.month': '월간',
    'calendar.new_booking': '신규 예약 접수',
    'calendar.all_therapists': '전체 마사지사',
    'calendar.today': '오늘',
    'calendar.no_therapists': '등록된 마사지사가 없습니다.',
    'calendar.legend.pending': '대기',
    'calendar.legend.confirmed': '확정',
    'calendar.legend.completed': '완료',
    'calendar.legend.cancelled': '취소',

    // List Page
    'list.title': '예약 목록 (리스트)',
    'list.filter.start': '시작일',
    'list.filter.end': '종료일',
    'list.table.client': '고객명',
    'list.table.phone': '연락처',
    'list.table.therapist': '담당 마사지사',
    'list.table.room': '관리실',
    'list.table.time': '예약 시간',
    'list.table.status': '상태',
    'list.table.creator': '접수자',
    'list.table.created_at': '접수 일시',
    'list.table.actions': '관리',
    'list.no_data': '조건에 해당하는 예약 내역이 없습니다.',

    // Booking Modal
    'booking.modal.new': '신규 예약 접수',
    'booking.modal.edit': '예약 상세 및 수정',
    'booking.modal.client_name': '고객 이름',
    'booking.modal.client_phone': '고객 연락처',
    'booking.modal.room_number': '룸 번호',
    'booking.modal.start_time': '시작 시간',
    'booking.modal.duration': '코스 시간 (분)',
    'booking.modal.therapist': '마사지사 선택',
    'booking.modal.status': '예약 상태',
    'booking.modal.notes': '요청 사항 / 메모',
    'booking.modal.price': '금액 ($)',
    'booking.modal.save': '예약 저장',
    'booking.modal.saving': '저장 중...',
    'booking.modal.cancel_booking': '예약 취소 처리',
    'booking.modal.cancel.type_label': '취소 유형 선택',
    'booking.modal.cancel.type_normal': '정상 취소 (페널티 없음)',
    'booking.modal.cancel.type_request': '취소 요청 (페널티 1점)',
    'booking.modal.cancel.type_noshow': '노쇼 - 연락 없이 불참 (페널티 3점)',
    'booking.modal.cancel.confirm_btn': '선택한 유형으로 예약 취소',
    'booking.modal.cancel.back_btn': '이전으로',
    'booking.modal.close': '닫기',
    'booking.modal.error.overlap': '선택한 마사지사가 해당 시간에 이미 예약되어 있습니다.',
    'booking.modal.error.fill': '필수 입력 항목을 모두 작성해주세요.',
    'booking.modal.error.db': '데이터베이스 저장 중 오류가 발생했습니다.',

    // Blacklist
    'blacklist.title': '취소자 블랙리스트',
    'blacklist.subtitle': '예약 취소가 잦아 주의가 필요한 고객 목록입니다.',
    'blacklist.add': '블랙리스트 수동 등록',
    'blacklist.client': '고객 정보',
    'blacklist.reason': '차단 사유',
    'blacklist.date': '등록일',
    'blacklist.status': '경고 수준',
    'blacklist.status.high': '위험 (당일 취소 3회 이상)',
    'blacklist.status.medium': '경보 (전체 취소 3회 이상)',
    'blacklist.status.low': '주의',
    'blacklist.action': '해제',
    'blacklist.guide.title': '💡 블랙리스트 분석 가이드',
    'blacklist.guide.desc': '이 화면은 예약 데이터 내의 취소 기록을 바탕으로 **잦은 부도(No-Show) 및 취소 고객**을 분석하는 용도입니다. 취소 비율이 높고 건수가 잦은 고객은 예약 접수 시 확인 전화를 하거나 사전 예치금을 요청하여 기회비용 손실을 예방하십시오.',
    'blacklist.filter.search_placeholder': '고객 이름, 연락처 검색...',
    'blacklist.filter.label': '필터 대상:',
    'blacklist.filter.all': '전체 취소 이력 (1회 이상)',
    'blacklist.filter.warning': '⚠️ 주의 대상 (3회 이상)',
    'blacklist.filter.danger': '🚨 블랙리스트 위험 (5회 이상)',
    'blacklist.filter.penalty_all': '전체 페널티 대상 (1점 이상)',
    'blacklist.filter.penalty_warning': '⚠️ 경고 대상 (3점 이상)',
    'blacklist.filter.penalty_danger': '🚨 블랙리스트 위험 (5점 이상)',
    'blacklist.sync': '분석 동기화',
    'blacklist.loading': '취소자 데이터를 종합 집계하는 중...',
    'blacklist.no_records': '조건에 부합하는 취소 이력 고객이 존재하지 않습니다.',
    'blacklist.table.no': 'No',
    'blacklist.table.level': '등급',
    'blacklist.table.penalty_points': '누적 페널티',
    'blacklist.table.cancel_count': '취소 횟수',
    'blacklist.table.normal_count': '정상 이용',
    'blacklist.table.cancel_rate': '취소율(%)',
    'blacklist.table.loss': '누적 기회손실',
    'blacklist.table.avg_time': '평균 취소 소요 시간',
    'blacklist.table.last_cancel': '최근 취소 일시',
    'blacklist.table.details': '세부 기록',
    'blacklist.badge.normal': '일반',
    'blacklist.badge.warning': '⚠️ 주의 대상',
    'blacklist.badge.danger': '🚨 블랙리스트 위험',
    'blacklist.times': '회',
    'blacklist.currency': '',
    'blacklist.no_log': '기록 없음',
    'blacklist.detail.title': '{name} 고객님의 예약 취소 상세 기록 ({count}건)',
    'blacklist.detail.status.cancelled': '취소됨',
    'blacklist.detail.booked_use': '예약 이용: ',
    'blacklist.detail.created_at': '접수 일시: ',
    'blacklist.detail.cancelled_at': '취소 일시: ',
    'blacklist.detail.duration': '등록 후 취소까지: ',
    'blacklist.detail.therapist': '담당 마사지사: ',
    'blacklist.detail.price': '금액: ',
    'blacklist.detail.no_assign': '미배정 (삭제됨)',
    'blacklist.detail.cancel_type': '취소 유형: ',
    'blacklist.detail.penalty': '부과 페널티: ',
    'blacklist.badge.penalty': '점',

    // Schedule
    'schedule.title': '근무 여부 설정',
    'schedule.subtitle': '마사지사들의 일자별 근무 및 배정 상태를 설정합니다.',
    'schedule.on_duty': '근무 중',
    'schedule.off_duty': '휴무',
    'schedule.title_main': '🗓️ 마사지사 근무일 현황',
    'schedule.mode.week': '주간',
    'schedule.mode.month': '월간',
    'schedule.filter.all_therapists': '전체 마사지사 보기',
    'schedule.filter.therapist_suffix': ' (마사지사)',
    'schedule.edit_guide': '* 날짜 칸을 클릭해 From ~ To 일정을 일괄 편집할 수 있습니다. (3주 범위 내 제한)',
    'schedule.loading': '근무 일정을 동기화하는 중...',
    'schedule.view_only': '조회전용',
    'schedule.weekday.sun': '일',
    'schedule.weekday.mon': '월',
    'schedule.weekday.tue': '화',
    'schedule.weekday.wed': '수',
    'schedule.weekday.thu': '목',
    'schedule.weekday.fri': '금',
    'schedule.weekday.sat': '토',
    'schedule.error.past_date': '지난 날짜의 근무 일정은 수정할 수 없습니다.',
    'schedule.error.from_past': '시작 날짜는 오늘 이전일 수 없습니다.',
    'schedule.error.max_limit': '설정 가능한 최대 범위는 오늘 기준 3주(21일)까지입니다.',
    'schedule.error.to_before_from': '종료 날짜는 시작 날짜보다 빠를 수 없습니다.',
    'schedule.error.select_therapist': '마사지사를 선택해 주세요.',
    'schedule.error.past_save': '과거 날짜를 포함한 근무 일정은 저장할 수 없습니다.',
    'schedule.modal.title': '마사지사 근무 일정 설정',
    'schedule.modal.therapist': '대상 마사지사',
    'schedule.modal.from': '시작 날짜 (From)',
    'schedule.modal.to': '종료 날짜 (To)',
    'schedule.modal.limit_info': '* 근무 일정은 오늘 날짜로부터 최대 3주(21일)까지만 설정 및 변경이 가능합니다.',
    'schedule.modal.type_title': '근무 형태 설정',
    'schedule.type.full': '근무 (종일)',
    'schedule.type.am_half': '오전반차 (오후근무)',
    'schedule.type.pm_half': '오후반차 (오전근무)',
    'schedule.type.off': '휴무 (종일)',
    'schedule.type.undecided': '미정 (-)',
    'schedule.save_button': '근무 저장',
    'schedule.saving': '저장 중...',

    // Therapist Settings
    'therapist.title': '마사지사 관리 (오늘의 고급지정)',
    'therapist.subtitle': '고급 마사지사 지정 요율 및 자동 배정 비중을 설정합니다.',
    'therapist.premium_rate': '고급 지정 비율 (%)',
    'therapist.auto_assign': '자동 배정 가중치',
    'therapist.name': '마사지사 이름',
    'therapist.phone': '연락처',
    'therapist.email': '이메일',
    'therapist.add': '신규 마사지사 추가',
    'therapist.save': '변경사항 저장',
    'therapist.massage_type': '마사지 속성 (건식/습식)',
    'therapist.type.dry': '건식 전담',
    'therapist.type.wet': '습식 전담',
    'therapist.type.both': '건식 & 습식 (모두 가능)',

    // Pricing Settings
    'pricing.title': '마사지 요금 관리',
    'pricing.category': '서비스 유형',
    'pricing.category.dry': '건식 (Dry)',
    'pricing.category.wet': '습식 (Wet/Bath)',
    'pricing.category.combo': '콤보 (Combo)',
    'pricing.bath_service': '습식 (Bath) 서비스',
    'pricing.massage_service': '건식 (Massage) 서비스',
    'pricing.bath_price': '습식 요금 ($)',
    'pricing.bath_duration': '습식 소요시간 (분)',
    'pricing.bath_weight': '습식 가중치',
    'pricing.massage_price': '건식 요금 ($)',
    'pricing.massage_duration': '건식 소요시간 (분)',
    'pricing.massage_weight': '건식 가중치',
    'pricing.total_applied_price': '예약 화면 적용 요금 ($)',
    'pricing.total_duration': '전체 소요시간 (분)',

    // Employee Settings
    'employee.title': '프론트 직원 등록 관리',
    'employee.name': '직원 이름',
    'employee.role': '권한',
    'employee.email': '이메일',
    'employee.phone': '연락처',
    'employee.add': '신규 직원 추가',
    'employee.save': '저장',
    'employee.add_title': '신규 직원 계정 추가',
    'employee.list_title': '프론트 근무 직원 명단',
    'employee.edit_title': '직원 정보 수정',
    'employee.role.staff_desc': 'Staff (일반 프론트 직원)',
    'employee.role.manager_desc': 'Manager (대시보드 총괄 관리자)',
    'employee.required_fields': '이름, 이메일, 비밀번호는 필수 입력 사항입니다.',
    'employee.uuid_error': '계정 정보(UUID)를 발급받지 못했습니다.',
    'employee.db_error': '인증계정({email})은 생성되었으나 권한 정보 입력에 실패했습니다: {msg}',
    'employee.add_success': '성공: \'{name}\' 직원이 등록되었습니다! (초기 비번: {password})',
    'employee.edit_success': '성공: \'{name}\' 직원의 정보가 수정되었습니다.',
    'employee.delete_confirm': '직원 \'{name}\'을(를) 정말로 삭제하시겠습니까?\n(인증 레코드 및 모든 예약 연계 참조 정보가 함께 정리될 수 있습니다.)',
    'employee.delete_success': '성공: \'{name}\' 권한 데이터가 정리되었습니다.',
    'employee.reset_prompt': '\'{name}\' 직원의 새 비밀번호를 입력해주세요.\n(미입력 시 \'password123\'으로 설정됩니다.)',
    'employee.reset_success': '성공: \'{name}\' 직원의 비밀번호가 초기화되었습니다! (새 비밀번호: {password})',
    'employee.self_delete_error': '자기 자신(현재 세션 유저)의 계정은 삭제할 수 없습니다.',
    'employee.info_label': '직원 정보',
    'employee.edit_tooltip': '정보 수정',
    'employee.reset_tooltip': '비밀번호 초기화',
    'employee.self_delete_tooltip': '본인 삭제 불가',
    'employee.delete_tooltip': '직원 삭제',
    'employee.creating': '인증계정 발급 중...',
    'employee.saving': '저장 중...',

    // Audit logs
    'history.title': '변경 이력 조회',
    'history.time': '변경 일시',
    'history.user': '작업자',
    'history.action': '작업 내용',
    'history.details': '상세 내용',
    'history.title_admin': '변경 이력 조회 (관리자 전용)',
    'history.refresh': '새로고침',
    'history.filter.type': '이력 종류',
    'history.filter.all': '전체 변경 이력',
    'history.filter.reservation': '예약 변경 이력',
    'history.filter.schedule': '근무 변경 이력',
    'history.filter.therapist': '마사지사 변경 이력',
    'history.filter.employee': '직원 변경 이력',
    'history.filter.period': '조회 기간',
    'history.loading': '이력 데이터를 불러오는 중...',
    'history.no_records': '조회 범위 내에 조건에 맞는 변경 이력이 존재하지 않습니다.',
    'history.table.time': '작업 일시',
    'history.table.type': '종류',
    'history.table.action': '액션',
    'history.table.user': '수행자',
    'history.table.target': '대상 정보',
    'history.table.details': '상세 변경 내용',
    'history.type.reservation': '예약',
    'history.type.schedule': '근무 일정',
    'history.type.therapist': '마사지사',
    'history.type.employee': '직원',
    'history.type.other': '기타',
    'history.action.create': '등록/설정',
    'history.action.update': '수정/변경',
    'history.action.delete': '초기화',
    'history.action.cancel': '예약 취소',
    'history.target.schedule': '근무 스케줄',
    'history.system': '시스템',
    'history.no_info': '정보 없음',
    'history.pagination.page': '페이지 {current} / {total}',
    'history.pagination.prev': '이전',
    'history.pagination.next': '다음',

    // Stats
    'stats.title': '예약 현황 통계',
    'stats.total_bookings': '누적 예약 수',
    'stats.revenue': '누적 매출',
    'stats.cancellation_rate': '취소율',
    'stats.by_therapist': '마사지사별 예약 분포',
    'stats.period.daily': '일간',
    'stats.period.weekly': '주간',
    'stats.period.monthly': '월간',
    'stats.navigator.today': '오늘',
    'stats.loading': '통계 데이터를 로딩하는 중...',
    'stats.kpi.total_bookings': '총 예약 건수',
    'stats.kpi.total_revenue': '총 매출액',
    'stats.kpi.premium_ratio': '고급 마사지 비중',
    'stats.kpi.top_therapist': '우수 마사지사 (최다건)',
    'stats.kpi.cancelled_label': '취소건: {count}건 (비율 {rate}%)',
    'stats.kpi.revenue_label': '확정된 예약 기준 정산 금액',
    'stats.kpi.premium_label': '$120 이상 코스: {count}건',
    'stats.kpi.top_therapist_label': '누적 배정: {count}건 / ${revenue}',
    'stats.kpi.no_data': '데이터가 없습니다.',
    'stats.kpi.none': '없음',
    'stats.chart.ranking_title': '마사지사별 실적 현황 랭킹',
    'stats.chart.sort.count': '예약 건수순',
    'stats.chart.sort.revenue': '매출액순',
    'stats.chart.off_duty': '휴무',
    'stats.chart.premium_role': '고급담당',
    'stats.chart.trend_title': '{period} 예약 건수 추이',
    'stats.chart.trend.hour': '시간대별',
    'stats.chart.trend.day': '요일별',
    'stats.chart.trend.date': '일별',
    'stats.chart.trend.unit': '단위: 예약 건수',
    'stats.chart.trend.confirmed': '확정: {count}건',
    'stats.chart.trend.daily_desc': '오늘 예약은 시간대별로 균등히 배정되는 경향을 보입니다. 정리가 필요한 시간대를 분석하여 직원을 추가 배치하십시오.',
    'stats.chart.trend.weekly_desc': '요일별 예약 분포를 통해 주말 및 특정 요일의 쏠림 현상을 분석하고 마사지사 휴무 일정을 조율할 수 있습니다.',
    'stats.chart.trend.monthly_desc': '월별 누적 예약을 통해 매달 전체 예약의 활성화 주기 및 계절별 예약 추이를 한눈에 추적합니다.',
    'stats.warning.cancellation_title': '⚠️ 예약 취소 알림 및 분석',
    'stats.warning.cancellation_desc': '이 기간 동안 총 {count}건의 예약이 취소되었습니다. 취소된 예약으로 인한 예상 기회비용 손실액은 약 ${loss}입니다. 잦은 취소 시간대 또는 취소 사유를 파악하여 예약 예치금(노쇼 방지) 등의 도입을 고려해 주십시오.',

    // Audit logs dynamic template
    'log.therapist.add': '[마사지사 추가] \'{name}\' (이메일: {email}, 고급지정: {premium})',
    'log.therapist.active_toggle': '\'{name}\' 마사지사의 근무 상태를 [{status}]로 변경함',
    'log.therapist.premium_toggle': '\'{name}\' 마사지사의 고급 전담 지정을 [{status}]함',
    'log.therapist.reset_password': '\'{name}\' 마사지사의 비밀번호를 초기화함',
    'log.therapist.link_account': '\'{name}\' 마사지사의 로그인 계정(연동)을 생성함 (이메일: {email})',
    'log.therapist.update': '\'{name}\' 마사지사의 정보 수정 - [{changes}]',
    'log.therapist.delete': '\'{name}\' 마사지사를 삭제 처리함',
    'log.therapist.val.premium_yes': '예',
    'log.therapist.val.premium_no': '아니오',
    'log.therapist.val.status_on': '근무',
    'log.therapist.val.status_off': '휴무',
    'log.therapist.val.premium_assign': '설정',
    'log.therapist.val.premium_unassign': '해제',
    'log.therapist.val.change_name': '이름: {old} -> {new}',
    'log.therapist.val.change_email': '이메일: {old} -> {new}',
    'log.therapist.val.change_phone': '연락처: {old} -> {new}',

    'log.employee.add': '[직원 추가] \'{name}\' (이메일: {email}, 권한: {role})',
    'log.employee.update': '\'{name}\' 직원의 정보 수정 - [{changes}]',
    'log.employee.reset_password': '\'{name}\' 직원의 비밀번호를 초기화함',
    'log.employee.delete': '\'{name}\' 직원을 삭제 처리함',
    'log.employee.val.role_manager': '관리자',
    'log.employee.val.role_staff': '직원',
    'log.employee.val.change_name': '이름: {old} -> {new}',
    'log.employee.val.change_role': '권한: {old} -> {new}',
    'log.employee.val.change_email': '이메일: {old} -> {new}',
    'log.employee.val.change_phone': '연락처: {old} -> {new}',

    'log.reservation.update': '예약 정보 변경 - [{changes}]',
    'log.reservation.update_no_changes': '예약 정보 수정 (변경사항 없음)',
    'log.reservation.cancel': '예약 취소 - 고객: {name}',
    'log.reservation.val.change_client': '고객명: {old} -> {new}',
    'log.reservation.val.change_phone': '연락처: {old} -> {new}',
    'log.reservation.val.change_price': '금액: ${old} -> ${new}',
    'log.reservation.val.change_time': '시간: {old} -> {new}',
    'log.reservation.val.change_date_time': '일시: {old} -> {new}',
    'log.reservation.val.change_therapist': '마사지사: {old} -> {new}',
  },
  en: {
    // App & Layout
    'app.title': 'Riviera Health Spa Booking',
    'app.subtitle': 'Riviera Health Spa Booking System',
    'nav.today_schedule': "Today's Work schedule",
    'nav.calendar': 'Booking Board (Calendar)',
    'nav.list': 'Booking List',
    'nav.blacklist': 'Cancellation Blacklist',
    'nav.schedule': 'Duty Schedule',
    'nav.pricing': 'Pricing',
    'nav.priority': 'Priority Management',
    'nav.therapist': 'Manage Therapists (Premium)',
    'nav.employee': 'Manage Staff',
    'nav.history': 'Audit History',
    'nav.stats': 'Statistics',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'user.role.manager': 'Manager',
    'user.role.staff': 'Staff',
    'user.role.therapist': 'Therapist',
    'user.syncing': 'Synchronizing data...',

    // Login
    'login.title': 'System Login',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.submitting': 'Logging in...',
    'login.error': 'Login failed. Please check your email and password.',
    'login.info': 'Manager PW: 12345! / Staff & Therapist PW: 123456',

    // Calendar & Modes
    'calendar.title': 'Booking Board (Calendar)',
    'calendar.mode.day': 'Day',
    'calendar.mode.week': 'Week',
    'calendar.mode.month': 'Month',
    'calendar.new_booking': 'New Booking',
    'calendar.all_therapists': 'All Therapists',
    'calendar.today': 'Today',
    'calendar.no_therapists': 'No registered therapists.',
    'calendar.legend.pending': 'Pending',
    'calendar.legend.confirmed': 'Confirmed',
    'calendar.legend.completed': 'Completed',
    'calendar.legend.cancelled': 'Cancelled',

    // List Page
    'list.title': 'Booking List',
    'list.filter.start': 'Start Date',
    'list.filter.end': 'End Date',
    'list.table.client': 'Client Name',
    'list.table.phone': 'Phone Number',
    'list.table.therapist': 'Therapist',
    'list.table.room': 'Room',
    'list.table.time': 'Time Slot',
    'list.table.status': 'Status',
    'list.table.creator': 'Booked By',
    'list.table.created_at': 'Booked At',
    'list.table.actions': 'Actions',
    'list.no_data': 'No bookings found in this range.',

    // Booking Modal
    'booking.modal.new': 'New Booking',
    'booking.modal.edit': 'Booking Details & Edit',
    'booking.modal.client_name': 'Client Name',
    'booking.modal.client_phone': 'Phone Number',
    'booking.modal.room_number': 'Room Number',
    'booking.modal.start_time': 'Start Time',
    'booking.modal.duration': 'Duration (Min)',
    'booking.modal.therapist': 'Select Therapist',
    'booking.modal.status': 'Status',
    'booking.modal.notes': 'Special Requests / Notes',
    'booking.modal.price': 'Price ($)',
    'booking.modal.save': 'Save Booking',
    'booking.modal.saving': 'Saving...',
    'booking.modal.cancel_booking': 'Cancel Booking',
    'booking.modal.cancel.type_label': 'Select Cancellation Type',
    'booking.modal.cancel.type_normal': 'Normal Cancellation (No penalty)',
    'booking.modal.cancel.type_request': 'Cancellation Request (1 pt)',
    'booking.modal.cancel.type_noshow': 'No-Show - Did not show up (3 pts)',
    'booking.modal.cancel.confirm_btn': 'Cancel Reservation with Selected Type',
    'booking.modal.cancel.back_btn': 'Back',
    'booking.modal.close': 'Close',
    'booking.modal.error.overlap': 'The therapist is already booked at this time.',
    'booking.modal.error.fill': 'Please fill in all required fields.',
    'booking.modal.error.db': 'An error occurred while saving to the database.',

    // Blacklist
    'blacklist.title': 'Cancellation Blacklist',
    'blacklist.subtitle': 'List of clients who frequently cancel bookings and require caution.',
    'blacklist.add': 'Manual Block',
    'blacklist.client': 'Client Details',
    'blacklist.reason': 'Reason',
    'blacklist.date': 'Blocked Date',
    'blacklist.status': 'Alert Level',
    'blacklist.status.high': 'Critical (3+ Same-day Cancels)',
    'blacklist.status.medium': 'Warning (3+ Total Cancels)',
    'blacklist.status.low': 'Caution',
    'blacklist.action': 'Unblock',
    'blacklist.guide.title': '💡 Blacklist Analysis Guide',
    'blacklist.guide.desc': 'This view analyzes **frequent no-show and cancel clients** based on cancellation records. For clients with high cancellation rates/counts, verify by phone or request deposits to prevent cost loss.',
    'blacklist.filter.search_placeholder': 'Search client name, phone...',
    'blacklist.filter.label': 'Filter Targets:',
    'blacklist.filter.all': 'All cancellations (1+)',
    'blacklist.filter.warning': '⚠️ Caution Targets (3+)',
    'blacklist.filter.danger': '🚨 Blacklist Danger (5+)',
    'blacklist.filter.penalty_all': 'All Penalty Targets (1+ pts)',
    'blacklist.filter.penalty_warning': '⚠️ Warning Targets (3+ pts)',
    'blacklist.filter.penalty_danger': '🚨 Critical Targets (5+ pts)',
    'blacklist.sync': 'Sync Analytics',
    'blacklist.loading': 'Aggregating cancellation data...',
    'blacklist.no_records': 'No cancellation history found matching the filters.',
    'blacklist.table.no': 'No',
    'blacklist.table.level': 'Level',
    'blacklist.table.penalty_points': 'Penalty Points',
    'blacklist.table.cancel_count': 'Cancels',
    'blacklist.table.normal_count': 'Completed',
    'blacklist.table.cancel_rate': 'Cancel Rate(%)',
    'blacklist.table.loss': 'Est. Loss',
    'blacklist.table.avg_time': 'Avg. Time to Cancel',
    'blacklist.table.last_cancel': 'Last Cancel Date',
    'blacklist.table.details': 'Details',
    'blacklist.badge.normal': 'Normal',
    'blacklist.badge.warning': '⚠️ Warning',
    'blacklist.badge.danger': '🚨 Critical',
    'blacklist.times': 'time(s)',
    'blacklist.currency': '',
    'blacklist.no_log': 'No Record',
    'blacklist.detail.title': 'Cancellation log for {name} ({count} items)',
    'blacklist.detail.status.cancelled': 'Cancelled',
    'blacklist.detail.booked_use': 'Booked Slot: ',
    'blacklist.detail.created_at': 'Booked At: ',
    'blacklist.detail.cancelled_at': 'Cancelled At: ',
    'blacklist.detail.duration': 'Time to Cancel: ',
    'blacklist.detail.therapist': 'Therapist: ',
    'blacklist.detail.price': 'Price: ',
    'blacklist.detail.no_assign': 'Unassigned (Deleted)',
    'blacklist.detail.cancel_type': 'Cancel Type: ',
    'blacklist.detail.penalty': 'Penalty: ',
    'blacklist.badge.penalty': 'pt(s)',

    // Schedule
    'schedule.title': 'Duty Schedule',
    'schedule.subtitle': 'Manage working status and assignments of therapists.',
    'schedule.on_duty': 'On Duty',
    'schedule.off_duty': 'Off Duty',
    'schedule.title_main': '🗓️ Therapist Duty Schedule',
    'schedule.mode.week': 'Week',
    'schedule.mode.month': 'Month',
    'schedule.filter.all_therapists': 'All Therapists',
    'schedule.filter.therapist_suffix': ' (Therapist)',
    'schedule.edit_guide': '* Click on any date cell to batch edit schedules (limited to 3 weeks).',
    'schedule.loading': 'Synchronizing duty schedule...',
    'schedule.view_only': 'View Only',
    'schedule.weekday.sun': 'Sun',
    'schedule.weekday.mon': 'Mon',
    'schedule.weekday.tue': 'Tue',
    'schedule.weekday.wed': 'Wed',
    'schedule.weekday.thu': 'Thu',
    'schedule.weekday.fri': 'Fri',
    'schedule.weekday.sat': 'Sat',
    'schedule.error.past_date': 'Schedules in the past cannot be modified.',
    'schedule.error.from_past': 'Start date cannot be before today.',
    'schedule.error.max_limit': 'Maximum allowed range is 3 weeks (21 days) from today.',
    'schedule.error.to_before_from': 'End date cannot be earlier than start date.',
    'schedule.error.select_therapist': 'Please select a therapist.',
    'schedule.error.past_save': 'Schedules containing past dates cannot be saved.',
    'schedule.modal.title': 'Therapist Duty Settings',
    'schedule.modal.therapist': 'Target Therapist',
    'schedule.modal.from': 'Start Date (From)',
    'schedule.modal.to': 'End Date (To)',
    'schedule.modal.limit_info': '* Duty schedules can only be set or changed up to 3 weeks (21 days) from today.',
    'schedule.modal.type_title': 'Duty Type Settings',
    'schedule.type.full': 'On Duty (Full Day)',
    'schedule.type.am_half': 'AM Half Duty (PM Work)',
    'schedule.type.pm_half': 'PM Half Duty (AM Work)',
    'schedule.type.off': 'Off Duty (Full Day)',
    'schedule.type.undecided': 'Undecided (-)',
    'schedule.save_button': 'Save Duty',
    'schedule.saving': 'Saving...',

    // Therapist Settings
    'therapist.title': 'Manage Therapists (Premium)',
    'therapist.subtitle': 'Configure therapist priority and auto-assignment rates.',
    'therapist.premium_rate': 'Premium Rate (%)',
    'therapist.auto_assign': 'Auto-Assign Weight',
    'therapist.name': 'Therapist Name',
    'therapist.phone': 'Phone Number',
    'therapist.email': 'Email',
    'therapist.add': 'Add New Therapist',
    'therapist.save': 'Save Changes',
    'therapist.massage_type': 'Massage Specialty (Dry/Wet)',
    'therapist.type.dry': 'Dry Only',
    'therapist.type.wet': 'Wet Only',
    'therapist.type.both': 'Dry & Wet (Both)',

    // Pricing Settings
    'pricing.title': 'Massage Pricing Management',
    'pricing.category': 'Service Category',
    'pricing.category.dry': 'Dry Massage Only',
    'pricing.category.wet': 'Wet / Bath Service Only',
    'pricing.category.combo': 'Combo (Dry + Wet)',
    'pricing.bath_service': 'Bath Service (Wet)',
    'pricing.massage_service': 'Massage Service (Dry)',
    'pricing.bath_price': 'Bath Service Price ($)',
    'pricing.bath_duration': 'Bath Service Time (min)',
    'pricing.bath_weight': 'Bath Weight',
    'pricing.massage_price': 'Massage Service Price ($)',
    'pricing.massage_duration': 'Massage Service Time (min)',
    'pricing.massage_weight': 'Massage Weight',
    'pricing.total_applied_price': 'Total Applied Price ($)',
    'pricing.total_duration': 'Total Duration (min)',

    // Employee Settings
    'employee.title': 'Manage Front Desk Staff',
    'employee.name': 'Employee Name',
    'employee.role': 'Role',
    'employee.email': 'Email',
    'employee.phone': 'Phone Number',
    'employee.add': 'Add New Staff',
    'employee.save': 'Save',
    'employee.add_title': 'Add New Staff Account',
    'employee.list_title': 'Front Desk Staff List',
    'employee.edit_title': 'Edit Staff Info',
    'employee.role.staff_desc': 'Staff (General Front Desk)',
    'employee.role.manager_desc': 'Manager (Dashboard Admin)',
    'employee.required_fields': 'Name, email, and password are required fields.',
    'employee.uuid_error': 'Failed to issue account info (UUID).',
    'employee.db_error': 'Auth account ({email}) was created, but failed to insert role info: {msg}',
    'employee.add_success': 'Success: \'{name}\' has been registered! (Initial PW: {password})',
    'employee.edit_success': 'Success: Employee \'{name}\' has been updated.',
    'employee.delete_confirm': 'Are you sure you want to delete employee \'{name}\'?\n(Authentication record and all booking references will be cleaned up.)',
    'employee.delete_success': 'Success: Employee \'{name}\' role data has been removed.',
    'employee.reset_prompt': 'Please enter the new password for \'{name}\'.\n(Default is \'password123\')',
    'employee.reset_success': 'Success: \'{name}\'\'s password has been reset! (New PW: {password})',
    'employee.self_delete_error': 'You cannot delete your own account.',
    'employee.info_label': 'Staff Info',
    'employee.edit_tooltip': 'Edit Info',
    'employee.reset_tooltip': 'Reset Password',
    'employee.self_delete_tooltip': 'Cannot delete self',
    'employee.delete_tooltip': 'Delete Staff',
    'employee.creating': 'Creating account...',
    'employee.saving': 'Saving...',

    // Audit logs
    'history.title': 'Audit History',
    'history.time': 'Time',
    'history.user': 'User',
    'history.action': 'Action',
    'history.details': 'Details',
    'history.title_admin': 'Audit History (Admin Only)',
    'history.refresh': 'Refresh',
    'history.filter.type': 'Log Type',
    'history.filter.all': 'All History',
    'history.filter.reservation': 'Reservation History',
    'history.filter.schedule': 'Duty History',
    'history.filter.therapist': 'Therapist History',
    'history.filter.employee': 'Staff History',
    'history.filter.period': 'Query Period',
    'history.loading': 'Loading history logs...',
    'history.no_records': 'No logs found matching the criteria in the selected range.',
    'history.table.time': 'Time',
    'history.table.type': 'Type',
    'history.table.action': 'Action',
    'history.table.user': 'User',
    'history.table.target': 'Target Info',
    'history.table.details': 'Change Details',
    'history.type.reservation': 'Reservation',
    'history.type.schedule': 'Duty',
    'history.type.therapist': 'Therapist',
    'history.type.employee': 'Staff',
    'history.type.other': 'Other',
    'history.action.create': 'Create/Set',
    'history.action.update': 'Update/Change',
    'history.action.delete': 'Reset',
    'history.action.cancel': 'Cancel',
    'history.target.schedule': 'Duty Schedule',
    'history.system': 'System',
    'history.no_info': 'No Info',
    'history.pagination.page': 'Page {current} of {total}',
    'history.pagination.prev': 'Prev',
    'history.pagination.next': 'Next',

    // Stats
    'stats.title': 'Booking Statistics',
    'stats.total_bookings': 'Total Bookings',
    'stats.revenue': 'Total Revenue',
    'stats.cancellation_rate': 'Cancellation Rate',
    'stats.by_therapist': 'Bookings by Therapist',
    'stats.period.daily': 'Daily',
    'stats.period.weekly': 'Weekly',
    'stats.period.monthly': 'Monthly',
    'stats.navigator.today': 'Today',
    'stats.loading': 'Loading statistics...',
    'stats.kpi.total_bookings': 'Total Bookings',
    'stats.kpi.total_revenue': 'Total Revenue',
    'stats.kpi.premium_ratio': 'Premium Booking Rate',
    'stats.kpi.top_therapist': 'Top Therapist (Bookings)',
    'stats.kpi.cancelled_label': 'Cancelled: {count} ({rate}%)',
    'stats.kpi.revenue_label': 'Net revenue for confirmed bookings',
    'stats.kpi.premium_label': '$120+ Course: {count}',
    'stats.kpi.top_therapist_label': 'Booked: {count} times / ${revenue}',
    'stats.kpi.no_data': 'No data.',
    'stats.kpi.none': 'None',
    'stats.chart.ranking_title': 'Therapist Ranking by Performance',
    'stats.chart.sort.count': 'Sort by Bookings',
    'stats.chart.sort.revenue': 'Sort by Revenue',
    'stats.chart.off_duty': 'Off',
    'stats.chart.premium_role': 'Premium',
    'stats.chart.trend_title': 'Trend of Bookings ({period})',
    'stats.chart.trend.hour': 'By Hour',
    'stats.chart.trend.day': 'By Day',
    'stats.chart.trend.date': 'By Date',
    'stats.chart.trend.unit': 'Unit: Bookings',
    'stats.chart.trend.confirmed': 'Confirmed: {count}',
    'stats.chart.trend.daily_desc': 'Today\'s bookings are relatively distributed. Analyze peak hours and schedule staff accordingly.',
    'stats.chart.trend.weekly_desc': 'Weekly booking distribution helps analyze weekend peaks and optimize therapist off schedules.',
    'stats.chart.trend.monthly_desc': 'Monthly cumulative bookings track booking cycles and seasonal trend shifts.',
    'stats.warning.cancellation_title': '⚠️ Booking Cancellation Analysis',
    'stats.warning.cancellation_desc': 'A total of {count} bookings were cancelled during this period. The estimated opportunity loss is around ${loss}. Consider implementing deposits for peak hours or repeat cancellers.',

    // Audit logs dynamic template
    'log.therapist.add': '[Add Therapist] \'{name}\' (Email: {email}, Premium: {premium})',
    'log.therapist.active_toggle': 'Changed working status of therapist \'{name}\' to [{status}]',
    'log.therapist.premium_toggle': 'Changed premium designation of therapist \'{name}\' to [{status}]',
    'log.therapist.reset_password': 'Reset password for therapist \'{name}\'',
    'log.therapist.link_account': 'Created & linked login account for therapist \'{name}\' (Email: {email})',
    'log.therapist.update': 'Edited info for therapist \'{name}\' - [{changes}]',
    'log.therapist.delete': 'Deleted therapist \'{name}\'',
    'log.therapist.val.premium_yes': 'Yes',
    'log.therapist.val.premium_no': 'No',
    'log.therapist.val.status_on': 'On Duty',
    'log.therapist.val.status_off': 'Off Duty',
    'log.therapist.val.premium_assign': 'Assigned',
    'log.therapist.val.premium_unassign': 'Unassigned',
    'log.therapist.val.change_name': 'Name: {old} -> {new}',
    'log.therapist.val.change_email': 'Email: {old} -> {new}',
    'log.therapist.val.change_phone': 'Phone: {old} -> {new}',

    'log.employee.add': '[Add Staff] \'{name}\' (Email: {email}, Role: {role})',
    'log.employee.update': 'Edited info for staff \'{name}\' - [{changes}]',
    'log.employee.reset_password': 'Reset password for staff \'{name}\'',
    'log.employee.delete': 'Deleted staff \'{name}\'',
    'log.employee.val.role_manager': 'Manager',
    'log.employee.val.role_staff': 'Staff',
    'log.employee.val.change_name': 'Name: {old} -> {new}',
    'log.employee.val.change_role': 'Role: {old} -> {new}',
    'log.employee.val.change_email': 'Email: {old} -> {new}',
    'log.employee.val.change_phone': 'Phone: {old} -> {new}',

    'log.reservation.update': 'Booking Info Changed - [{changes}]',
    'log.reservation.update_no_changes': 'Booking Info Saved (No changes)',
    'log.reservation.cancel': 'Booking Cancelled - Client: {name}',
    'log.reservation.val.change_client': 'Client: {old} -> {new}',
    'log.reservation.val.change_phone': 'Phone: {old} -> {new}',
    'log.reservation.val.change_price': 'Price: ${old} -> ${new}',
    'log.reservation.val.change_time': 'Time: {old} -> {new}',
    'log.reservation.val.change_date_time': 'Date/Time: {old} -> {new}',
    'log.reservation.val.change_therapist': 'Therapist: {old} -> {new}',
  }
}

interface LanguageContextProps {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, fallback?: string) => string
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ko')

  useEffect(() => {
    const saved = localStorage.getItem('app_lang')
    if (saved === 'en' || saved === 'ko') {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('app_lang', lang)
  }

  const t = (key: string, fallback?: string): string => {
    const dict = translations[language]
    return dict[key] || fallback || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
